include ../../common.mk

#DEBUG=-g
DEBUG=-O3
#PERLMODDIR=/home/kzhou/perlmod
perlmodule=PolyaPeak.pm PolyPeak.pm UncoverPolyA.pm Peak.pm
scripts= rmpolya rmjgix swapESTid.pl cleanfastitle cleanshortread solex2fas
INSTALL=install
CXXFLAGS += $(DEBUG)

binaries = uniqueshortseq cleanshort

all : update perlmod $(binaries)

update : ${scripts}
	${INSTALL} $? ${BINDIR}
	touch $@

perlmod : $(perlmodule)
	cp $^ $(PERLLIBDIR)
	touch $@

uniqueshortseq : uniqueshortseq.o
	$(CXX) $(CXXFLAGS) -o $@ $^
	cp $@ $(BINDIR)

cleanshort : cleanshort.o
	$(CXX) $(CXXFLAGS) -o $@ $^
	cp $@ $(BINDIR)

install : $(scripts) $(binaries)
	$(INSTALL) $^ $(BINDIR)
	cp $(perlmodule) $(PERLLIBDIR)

clean :
	-rm *.o
	-rm $(binaries)
